### ISSUE TITLE
代码如何混淆才可编译和运行？

### ISSUE THREAD

**Issue by ACPMMD** [LS95/CodeObfuscationForC-#2]
代码如何混淆才可编译和运行？
#include <stdio.h>
int main(int argc, char *argv[])
{
    printf("hello");
    return 0;
}
混淆后是这样的：
#include <stdio.h>

d7e112e548eda222intd7e112e548eda222 d7e112e548eda222maind7e112e548eda222(d7e112e548eda222intd7e112e548eda222 d7e112e548eda222argcd7e112e548eda222, d7e112e548eda222chard7e112e548eda222 *d7e112e548eda222argvd7e112e548eda222[])
{
    d7e112e548eda222printfd7e112e548eda222("\d7e112e548eda222x68d7e112e548eda222\d7e112e548eda222x65d7e112e548eda222\d7e112e548eda222x6cd7e112e548eda222\d7e112e548eda222x6cd7e112e548eda222\d7e112e548eda222x6fd7e112e548eda222");
    d7e112e548eda222returnd7e112e548eda222 d7e112e548eda2220d7e112e548eda222;
}
编译报错：
![image](https://user-images.githubusercontent.com/16660307/109252851-73fec200-7829-11eb-8e62-76e96828ce5d.png)

**Comment by LS95** [comment]
删掉一些头文件
